FROM python:3.11-slim
WORKDIR /app
COPY requirements_diabetes.txt .
RUN pip install --no-cache-dir -r requirements_diabetes.txt
COPY . .
EXPOSE 8000
CMD ["uvicorn", "api_diabetes:app", "--host", "0.0.0.0", "--port", "8000"]
